pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/Er-TanviKhare/expense-tracker-devops.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t expense-backend ./backend'
            }
        }

        stage('Build Frontend Image') {
            steps {
                sh 'docker build -t expense-frontend ./frontend'
            }
        }

        stage('Deploy Containers') {
            steps {
                sh '''
                docker stop backend || true
                docker rm backend || true
                docker stop frontend || true
                docker rm frontend || true

                docker run -d -p 5000:5000 --name backend expense-backend
                docker run -d -p 8081:80 --name frontend expense-frontend
                '''
            }
        }
    }
}